CREATE TABLE Gaming.Platforms
(
	PlatformId int NOT NULL identity(1,1) PRIMARY KEY,
	PlatformName NVARCHAR(32) NOT NULL,
	OnlinePlayers int NOT NULL,
	CreatedOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET()),
    UpdatedOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET())
)