CREATE TABLE Gaming.Company
(
	CompanyId int NOT NULL identity(1,1) PRIMARY KEY,
	Name NVARCHAR(32) NOT NULL,
	FoundedDate DATETIMEOFFSET NOT NULL,
	CreatedOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET()),
    UpdatedOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET())
)