CREATE TABLE Gaming.Game
(
	GameId int NOT NULL identity(1,1),
	CompanyId int NOT NULL,
	PlatformId int NOT NULL,
	Title NVARCHAR(32) NOT NULL,
	Price double NOT NULL,
	ReleaseDate DATETIMEOFFSET NOT NULL,
	Rating char NOT NULL,
	CreatedOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET()),
    UpdatedOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET())
)