CREATE TABLE Players.Streamers
(
	StreamerId int NOT NULL identity(1,1) PRIMARY KEY,
	StreamerName NVARCHAR(32) NOT NULL,
	Income int NOT NULL,
	StreamPlatform NVARCHAR(32) NOT NULL,
	Subscribers int NOT NULL,
	CreatedOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET()),
    UpdatedOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET())
);